---
# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# glance-images/tasks/main.yml

- name: Make images directory
  when: use_openstack
  become: yes
  file:
    path: "{{ image_dir }}"
    state: directory
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"

- name: Download Glance VM images
  when: use_openstack
  get_url:
    url: "{{ item.url }}"
    checksum: "{{ item.checksum }}"
    dest: "{{ image_dir }}/{{ item.name }}.qcow2"
  with_items: "{{ xos_images }}"
  register: glance_vm_result
  until: glance_vm_result is success
  retries: 5
  delay: 10

- name: Copy Glance VM images to profile directory
  when: use_openstack
  copy:
    remote_src: yes
    src: "{{ image_dir }}/{{ item.name }}.qcow2"
    dest: "/opt/cord_profile/images/{{ item.name }}.qcow2"
  with_items: "{{ xos_images }}"

