FROM {{ pull_docker_registry }}xosproject/xos:{{ pull_docker_tag }}

ARG XOS_GIT_COMMIT_HASH=unknown
ARG XOS_GIT_COMMIT_DATE=unknown

LABEL XOS_GIT_COMMIT_HASH=$XOS_GIT_COMMIT_HASH
LABEL XOS_GIT_COMMIT_DATE=$XOS_GIT_COMMIT_DATE

# Include local certificates for onboarding
ADD im_cert_chain.pem /usr/local/share/ca-certificates/local_certs.crt
RUN update-ca-certificates
