# ONOS dockerfile with XOS/CORD additions

FROM {{ onos_docker_image }}
MAINTAINER Zack Williams <zdw@cs.arizona.edu>

# Add SSL certs
COPY cord_root_ca.crt /usr/local/share/ca-certificates/cord_root_ca.crt
COPY cord_intermediate_ca.crt /usr/local/share/ca-certificates/cord_intermediate_ca.crt
RUN update-ca-certificates

# Create Java KeyStore from certs
RUN openssl x509 -in /usr/local/share/ca-certificates/cord_root_ca.crt \
      -outform der -out /usr/local/share/ca-certificates/cord_root_ca.der && \
    openssl x509 -in /usr/local/share/ca-certificates/cord_intermediate_ca.crt \
      -outform der -out /usr/local/share/ca-certificates/cord_intermediate_ca.der && \
    keytool -import -noprompt -storepass {{ trust_store_pw }} -alias cord_root_ca \
      -file /usr/local/share/ca-certificates/cord_root_ca.der \
      -keystore /usr/local/share/ca-certificates/cord_ca_certs.jks && \
    keytool -import -noprompt -storepass {{ trust_store_pw }} -alias cord_intermediate_ca \
      -file /usr/local/share/ca-certificates/cord_intermediate_ca.der \
      -keystore /usr/local/share/ca-certificates/cord_ca_certs.jks

# Updated onos-service to use the jks
COPY onos-service /root/onos/bin/onos-service
RUN chmod 755 /root/onos/bin/onos-service

