---
- hosts: xos
  sudo: no
  remote_user: ubuntu
  vars:
    homedir: /tmp
  tasks:
  - apt: update_cache=yes
    sudo: yes

  - apt: name={{ item }}
      state=present
    sudo: yes
    with_items:
    - git
    - make
    - python-novaclient
    - python-neutronclient
    - python-keystoneclient
    - python-glanceclient

  - git: repo=https://github.com/open-cloud/xos.git
      dest={{ ansible_env['PWD'] }}/xos

  - shell: make -f {{ ansible_env['PWD'] }}/xos/xos/configurations/common/Makefile.prereqs

  - copy: src={{ homedir }}/{{ item }}
      dest={{ ansible_env['PWD'] }}/xos/xos/configurations/cord-pod/
    with_items:
    - id_rsa
    - id_rsa.pub

  - file: path={{ ansible_env['PWD'] }}/xos/xos/configurations/cord-pod/id_rsa
      mode=0600

  - copy: src={{ homedir }}/admin-openrc.sh
      dest={{ ansible_env['PWD'] }}/xos/xos/configurations/cord-pod

  - copy: src={{ homedir }}/id_rsa
      dest={{ ansible_env['PWD'] }}/xos/xos/configurations/cord-pod/node_key

  - file: path={{ ansible_env['PWD'] }}/xos/xos/configurations/cord-pod/images
      state=directory

  - get_url: url=http://www.vicci.org/opencloud/trusty-server-cloudimg-amd64-disk1.img
      dest={{ ansible_env['PWD'] }}/xos/xos/configurations/cord-pod/images/trusty-server-multi-nic.img
